# Generated by Django 4.2.10 on 2024-05-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_insert_zipcode_data"),
    ]

    operations = []
