# Generated by Django 4.2.10 on 2024-05-14 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_auto_20240514_1227"),
    ]

    operations = []
